name : "terraform"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID}}
      AWS_REGION: "ap-south-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: init
        id: init
        run: terraform init
  
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve
